#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# The MIT License (MIT)
#
# Copyright (c) 2025  Authors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Authors: Petr Hracek <phracek@redhat.com>

import logging
import sys
import argparse
import urllib3

from eol_checker.custom_logger import setup_logger
from eol_checker.checker import ContainerEolChecker

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

logger = logging.getLogger(__name__)


def parse_args():
    """
    Parse the arguments.
    Returns:
        The parsed arguments.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-d", "--debug", action="store_true", default=False, help="Enable debug mode"
    )
    parser.add_argument(
        "--send-email",
        action="store_true",
        default=False,
        help="Send email to the SCL org members",
    )
    return parser


def main(args):
    """
    Main function to run the container EOL checker.
    Args:
        args: The parsed arguments.
    Returns:
        The exit code. 0 if successful, 1 if error.
    """
    print(f"Arguments: {args}")
    setup_logger(level=logging.DEBUG if args.debug else logging.INFO)
    checker = ContainerEolChecker(send_email=args.send_email)
    checker.run()
    sys.exit(0)


if __name__ == "__main__":
    parser = parse_args()
    main(parser.parse_args())
