[tox]
package = skip

[testenv]
commands = python3 -m pytest --color=yes -v --cov=eol_checker --cov-report=xml:coverage.xml
deps =
    pytest
    pytest-cov
    flexmock
    PyYAML
    requests
    xmltodict
    atlassian-python-api
    colorama
